version: "3.1"

volumes:
  postgresql-data:
services:
  database:
    image: postgis/postgis:14-3.2
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: raincell
      POSTGRES_PASSWORD: raincell

  pg-tileserv:
    image: pigeosolutions/pg_tileserv:latest-alpine-3.12
    entrypoint: [ "/wait-for-db.sh" ]
    depends_on:
      - database
    env_file:
      - pg_tileserv.env
    ports:
      - 7800:7800
    volumes:
      - ./config/:/config/