version: "3.1"
#
# Dockerfile to use to run a dev environment. Provides a postgis database and a pg_tileserv MVT server
#


volumes:
  postgresql-data:

services:
  database:
    image: postgis/postgis:14-3.2
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=raincell
      - POSTGRES_PASSWORD=raincell

  pg-tileserv:
    image: pigeosolutions/pg_tileserv:latest
    entrypoint: [ "/wait-for-db.sh" ]
    depends_on:
      - database
    env_file:
      - config/pg_tileserv/pg_tileserv.env
    environment:
      - TS_BASEPATH=/tiles/
      - TS_DBTIMEOUT=20
    ports:
      - 7800:7800