# Generated by Django 3.2.13 on 2022-06-09 12:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import raincell_core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CellRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.CharField(max_length=16, unique_for_date='recorded_day')),
                ('recorded_day', models.DateField(verbose_name='Day')),
                ('quantile25', models.JSONField(default=raincell_core.models.json_empty_default, null=True, verbose_name='Quantile25')),
                ('quantile50', models.JSONField(default=raincell_core.models.json_empty_default, help_text='This is the value we will use', null=True, verbose_name='Quantile50')),
                ('quantile75', models.JSONField(default=raincell_core.models.json_empty_default, null=True, verbose_name='Quantile75')),
                ('daily_mean', models.FloatField(blank=True, help_text='to be computed, based on quantile50 values', null=True, verbose_name='Daily Mean')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'Cell records: 1 cell record per pixel and per day',
            },
        ),
        migrations.AddIndex(
            model_name='cellrecord',
            index=models.Index(fields=['location', '-recorded_day'], name='raincell_co_locatio_857750_idx'),
        ),
        migrations.AddIndex(
            model_name='cellrecord',
            index=models.Index(fields=['-recorded_day'], name='raincell_co_recorde_f94685_idx'),
        ),
        migrations.AddIndex(
            model_name='cellrecord',
            index=models.Index(fields=['cell_id', '-recorded_day'], name='raincell_co_cell_id_069b79_idx'),
        ),
        migrations.AddConstraint(
            model_name='cellrecord',
            constraint=models.UniqueConstraint(fields=('location', 'recorded_day'), name='unique_location_day'),
        ),
        migrations.AddConstraint(
            model_name='cellrecord',
            constraint=models.UniqueConstraint(fields=('cell_id', 'recorded_day'), name='unique_cellid_day'),
        ),
    ]
