# Generated by Django 3.2.13 on 2022-06-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raincell_core', '0004_auto_20220610_0747'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rainrecord',
            name='raincell_co_cell_id_907aa7_idx',
        ),
        migrations.AlterField(
            model_name='rainrecord',
            name='cell_id',
            field=models.CharField(max_length=16, unique_for_date='recorded_day'),
        ),
        migrations.AddIndex(
            model_name='rainrecord',
            index=models.Index(fields=['cell_id', '-recorded_day'], name='raincell_co_cell_id_5df8c8_idx'),
        ),
    ]
