# Generated by Django 3.2.13 on 2022-06-08 07:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CellRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('quantile25', models.JSONField(null=True)),
                ('quantile50', models.JSONField(help_text='This is the value we will use', null=True)),
                ('quantile75', models.JSONField(null=True)),
                ('daily_mean', models.FloatField(blank=True, help_text='to be computed, based on quantile50 values', null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'Cell records: 1 cell record per pixel and per day',
            },
        ),
        migrations.AddConstraint(
            model_name='cellrecord',
            constraint=models.UniqueConstraint(fields=('location', 'day'), name='unique_location_day'),
        ),
    ]
