# Generated by Django 3.2.13 on 2022-06-08 09:02

from django.db import migrations, models
import raincell_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('raincell_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellrecord',
            name='daily_mean',
            field=models.FloatField(blank=True, help_text='to be computed, based on quantile50 values', null=True, verbose_name='Daily Mean'),
        ),
        migrations.AlterField(
            model_name='cellrecord',
            name='day',
            field=models.DateField(verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='cellrecord',
            name='quantile25',
            field=models.JSONField(default=raincell_core.models.json_empty_default, null=True, verbose_name='Quantile25'),
        ),
        migrations.AlterField(
            model_name='cellrecord',
            name='quantile50',
            field=models.JSONField(help_text='This is the value we will use', null=True, verbose_name='Quantile50'),
        ),
        migrations.AlterField(
            model_name='cellrecord',
            name='quantile75',
            field=models.JSONField(null=True, verbose_name='Quantile75'),
        ),
    ]
