# Generated by Django 3.2.13 on 2022-06-10 07:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raincell_core', '0002_create_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('cell_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'Geographical cell ("pixel")',
            },
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['location'], name='raincell_co_locatio_925f59_idx'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['cell_id'], name='raincell_co_cell_id_e44593_idx'),
        ),
        migrations.AddConstraint(
            model_name='cell',
            constraint=models.UniqueConstraint(fields=('location',), name='unique_location'),
        ),
    ]
