# Generated by Django 3.2.13 on 2022-06-08 09:07

from django.db import migrations, models
import raincell_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('raincell_core', '0002_auto_20220608_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellrecord',
            name='quantile50',
            field=models.JSONField(default=raincell_core.models.json_empty_default, help_text='This is the value we will use', null=True, verbose_name='Quantile50'),
        ),
        migrations.AlterField(
            model_name='cellrecord',
            name='quantile75',
            field=models.JSONField(default=raincell_core.models.json_empty_default, null=True, verbose_name='Quantile75'),
        ),
    ]
