# Generated by Django 3.2.13 on 2022-06-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raincell_core', '0003_auto_20220608_0907'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cellrecord',
            index=models.Index(fields=['location', '-day'], name='raincell_co_locatio_cbdafc_idx'),
        ),
        migrations.AddIndex(
            model_name='cellrecord',
            index=models.Index(fields=['-day'], name='raincell_co_day_be2032_idx'),
        ),
    ]
