# Generated by Django 3.2.13 on 2022-06-20 15:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import raincell_core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtomicRainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.CharField(max_length=16, unique_for_date='recorded_day')),
                ('recorded_time', models.DateTimeField(verbose_name='Date time')),
                ('quantile25', models.FloatField(null=True, verbose_name='Quantile25')),
                ('quantile50', models.FloatField(help_text='This is the value we will use', null=True, verbose_name='Quantile50')),
                ('quantile75', models.FloatField(null=True, verbose_name='Quantile75')),
                ('is_fake', models.BooleanField(default=False, help_text='used to flag fake data added by generate_fake_data admin command', null=True, verbose_name='Is fake data')),
            ],
            options={
                'verbose_name': 'Rain record: 1 rain record per cell and per datetime',
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'Geographical cell ("pixel")',
            },
        ),
        migrations.CreateModel(
            name='RainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.CharField(max_length=16, unique_for_date='recorded_day')),
                ('recorded_day', models.DateField(verbose_name='Day')),
                ('quantile25', models.JSONField(default=raincell_core.models.json_empty_default, null=True, verbose_name='Quantile25')),
                ('quantile50', models.JSONField(default=raincell_core.models.json_empty_default, help_text='This is the value we will use', null=True, verbose_name='Quantile50')),
                ('quantile75', models.JSONField(default=raincell_core.models.json_empty_default, null=True, verbose_name='Quantile75')),
                ('daily_mean', models.FloatField(blank=True, help_text='to be computed, based on quantile50 values', null=True, verbose_name='Daily Mean')),
                ('is_fake', models.BooleanField(default=False, help_text='used to flag fake data added by generate_fake_data admin command', null=True, verbose_name='Is fake data')),
            ],
            options={
                'verbose_name': 'Rain record: 1 rain record per cell and per day',
            },
        ),
        migrations.AddIndex(
            model_name='rainrecord',
            index=models.Index(fields=['-recorded_day'], name='raincell_co_recorde_54a43c_idx'),
        ),
        migrations.AddIndex(
            model_name='rainrecord',
            index=models.Index(fields=['cell_id', '-recorded_day'], name='raincell_co_cell_id_5df8c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='rainrecord',
            constraint=models.UniqueConstraint(fields=('cell_id', 'recorded_day'), name='rainrecord_unique_cellid_day'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['location'], name='raincell_co_locatio_925f59_idx'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['id'], name='raincell_co_id_89bb88_idx'),
        ),
        migrations.AddConstraint(
            model_name='cell',
            constraint=models.UniqueConstraint(fields=('location',), name='unique_location'),
        ),
        migrations.AddIndex(
            model_name='atomicrainrecord',
            index=models.Index(fields=['-recorded_time'], name='raincell_co_recorde_bf9bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='atomicrainrecord',
            index=models.Index(fields=['cell_id', '-recorded_time'], name='raincell_co_cell_id_db7852_idx'),
        ),
        migrations.AddConstraint(
            model_name='atomicrainrecord',
            constraint=models.UniqueConstraint(fields=('cell_id', 'recorded_time'), name='atomicrainrecord_unique_cellid_datetime'),
        ),
    ]
