# Generated by Django 3.2.13 on 2022-06-10 07:47

from django.db import migrations, models
import django.db.models.deletion
import raincell_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('raincell_core', '0003_auto_20220610_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_day', models.DateField(verbose_name='Day')),
                ('quantile25', models.JSONField(default=raincell_core.models.json_empty_default, null=True, verbose_name='Quantile25')),
                ('quantile50', models.JSONField(default=raincell_core.models.json_empty_default, help_text='This is the value we will use', null=True, verbose_name='Quantile50')),
                ('quantile75', models.JSONField(default=raincell_core.models.json_empty_default, null=True, verbose_name='Quantile75')),
                ('daily_mean', models.FloatField(blank=True, help_text='to be computed, based on quantile50 values', null=True, verbose_name='Daily Mean')),
                ('cell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raincell_core.cell', unique_for_date='recorded_day')),
            ],
            options={
                'verbose_name': 'Rain record: 1 rain record per cell and per day',
            },
        ),
        migrations.AddIndex(
            model_name='rainrecord',
            index=models.Index(fields=['-recorded_day'], name='raincell_co_recorde_54a43c_idx'),
        ),
        migrations.AddIndex(
            model_name='rainrecord',
            index=models.Index(fields=['cell_id', '-recorded_day'], name='raincell_co_cell_id_907aa7_idx'),
        ),
        migrations.AddConstraint(
            model_name='rainrecord',
            constraint=models.UniqueConstraint(fields=('cell_id', 'recorded_day'), name='rainrecord_unique_cellid_day'),
        ),
    ]
