# Generated by Django 3.2.13 on 2022-06-14 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raincell_core', '0008_update_MVT_function'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CellRecord',
        ),
    ]
