# Generated by Django 3.2.13 on 2022-06-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raincell_core', '0009_delete_cellrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='rainrecord',
            name='if_fake',
            field=models.BooleanField(default=False, help_text='used to flag fake data added by generate_fake_data admin command', null=True, verbose_name='Is fake data'),
        ),
    ]
