# Generated by Django 3.2.13 on 2022-06-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raincell_core', '0010_rainrecord_if_fake'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rainrecord',
            old_name='if_fake',
            new_name='is_fake',
        ),
    ]
